### ISSUE TITLE
`misMatchPercentage` is zero

### ISSUE THREAD

**Issue by MortenGregersen** [wswebcreation/wdio-native-app-compare#11]
**Environment (please complete the following information):**
 - Node.js version: 10.15.3
 - NPM version: 6.9.0
 - webdriver.io version: 5.7.15
 - wdio-native-app-compare-service version: 1.0.0

**Config of webdriver.io and the plugin**
```js
config.services = ['appium', 'native-app-compare'];
config.nativeAppCompare = {
    baselineFolder: './uitest/screenshots/baseline',
    screenshotPath: './uitest/screenshots',
    blockOutStatusBar: true,
    savePerDevice: true,
    rawMisMatchPercentage: true,
    imageNameFormat: '{tag}',
};
```

**Describe the bug**
If I manipulate the saved baseline screenshot to have a 10 % mismatch (by inserting a box) compared to the screenshot taken of the app it reports a mismatch percentage of 0 %.

**To Reproduce**
I just use the `compareScreen` command like this:
```js
const result = await driver.compareScreen(tag);
console.log('Result: ', result);
```
The result is logged like this:
```js
Result: { fileName: 'custody-accounts-details-page.png',
   folders:
    { actual: '/Users/bdumgr/MyProject/uitest/screenshots/actual/android_emulator',
      baseline: '/Users/bdumgr/MyProject/uitest/screenshots/baseline/android_emulator',
      diff: '/Users/bdumgr/MyProject/uitest/screenshots/diff/android_emulator' },
   misMatchPercentage: 0 }
```

I made a simple project which called the same things as `native-app-compare-service` and with the same images as `native-app-compare-service` saved in the baseline and actual folders. https://github.com/MortenGregersen/native-app-compare-bug
The simple project gave a meaningful result: 
```js
> node index.js
Actual:  /Users/bdumgr/native-app-compare-bug/actual.png
Baseline:  /Users/bdumgr/native-app-compare-bug/baseline.png
{ isSameDimensions: true,
  dimensionDifference: { width: 0, height: 0 },
  rawMisMatchPercentage: 10.24049961419753,
  misMatchPercentage: '10.24',
  diffBounds: { top: 559, left: 130, bottom: 807, right: 982 },
  analysisTime: 118,
  getImageDataUrl: [Function],
  getBuffer: [Function] }
```

**Expected behavior**
I would expect that `native-app-compare-service` would report the same `misMatchPercentage` as my simple project. As far as I can tell they call Resemble the same way.

**Screenshots**
![actual](https://user-images.githubusercontent.com/759680/56660725-7083d800-66a0-11e9-8380-5efd4c9d5352.png)
![baseline](https://user-images.githubusercontent.com/759680/56660730-711c6e80-66a0-11e9-8336-197fbd582f0d.png)

**Comment by wswebcreation** [comment]
Hi @MortenGregersen 

Thanks for the issue, I saw that I didn't test the API of ResembleJS correct. I made a quick fix so it should work now

https://github.com/wswebcreation/wdio-native-app-compare/releases/tag/1.0.1

Can you please download that version, I've checked it and it should be solved now. If it is solved, can you please close the issue?

**Comment by MortenGregersen** [comment]
Fixed 🥇
