### ISSUE TITLE
Question installing and using service

### ISSUE THREAD

**Issue by qvalero** [wswebcreation/wdio-native-app-compare#18]
Hello, 
I have installed the service following the readme and configured it:

```
services: [
        [ 'appium', {
            // Appium Service config
            // see details: https://webdriver.io/docs/appium-service.html
            logPath: `${BASE_REPORT_DIR}/logs`,
            args: {
                port: 4823,
                defaultCapabilities: [ '{"appium:noReset":true}' ],
                logNoColors: !DEBUG,
                logTimestamp: !DEBUG
            }
        }],
        [
            'native-app-compare',
            // The options
            {
                // Mandatory
                baselineFolder: 'test/image-baseline',
                screenshotPath: '.tmp/image-compare',
                autoSaveBaseline: true
            },
        ]
    ],
```

I am not able to use methods of your service using driver or browser. What I am missing in installation ?

![image](https://user-images.githubusercontent.com/63647610/82800645-4f318480-9e7c-11ea-947b-099754615bb1.png)

 - Node.js version: 13.12.0
 - NPM version: 6.14.4
 - webdriver.io version: 6
 - wdio-native-app-compare version: 1.2.0

**Comment by wswebcreation** [comment]
Hi @qvalero 

Thanks for filing an issue, they are not added to the types, that's why you don't see them. They should work if you run the tests, can you verify that?

**Comment by qvalero** [comment]
When I run tests I have the error:

`error TS2339: Property 'compareScreen' does not exist on type 'BrowserObject'.`

**Comment by wswebcreation** [comment]
ahh, for typescript, this module doesn't export the types, so you need to make them yourself

**Comment by qvalero** [comment]
What have I done:
Declare module in index.d.ts:
`declare module 'wdio-native-app-compare-service';`

Import it in my class:
`import driver from 'wdio-native-app-compare-service';`

Using it:
`expect(driver.compareScreen('test.png').misMatchPercentage).toEqual(0);`

But now error is: 
`wdio_native_app_compare_service_1.default.compareScreen is not a function`

Any idea on what is missing ?

**Comment by wswebcreation** [comment]
Yes, there are no interfaces in the module, so you need t create them yourself, this is not the way, maybe check this https://webdriver.io/docs/typescript.html#adding-custom-commands

**Comment by qvalero** [comment]
Ok thanks, in namespace WebdriverIO I have added:

`    
declare module 'wdio-native-app-compare-service';

export interface BrowserObject {
        compareScreen: typeof import('wdio-native-app-compare-service');
        compareElement: typeof import('wdio-native-app-compare-service');
        saveScreen: typeof import('wdio-native-app-compare-service');
        saveElement: typeof import('wdio-native-app-compare-service');
    }
}`

It is now working !
