### ISSUE TITLE
Full page comparison for native app

### ISSUE THREAD

**Issue by WasiqB** [wswebcreation/wdio-native-app-compare#20]
**Is your feature request related to a problem? Please describe.**

Currently, only the visible page is only verified and not the whole page.

**Describe the solution you'd like**

Ideally, whole page screenshot should be captured as baseline and while comparing, whole page should be compared. Same thing already happens in `wdio-image-comparison-service` when running Mobile web test, it compares full page.

**Comment by wswebcreation** [comment]
Thanks for the FR, I've been looking into this in the past and this is not as stable and straight forward as I thought it would be for a few reasons:

- the total height of the app is now known of iOS/Android
- iOS and Android work differently in what they show in their native tree (iOS shows much more, Android only what's in the view)
- with Web you can use JS injections to get more information of the page, not with native apps

and the list goes on

Unless someone else has a good suggestion I would say this is currently not possible

**Comment by wswebcreation** [comment]
Hi @WasiqB 

I'm going to close this for now because I can't find a way to do this in a stable way across all devices / OSes
