### ISSUE TITLE
Webdriver v7

### ISSUE THREAD

**Issue by qvalero** [wswebcreation/wdio-native-app-compare#21]
Hello,

Is this service working for webdriver v7 ?

Regards,

Quentin

**Comment by pfoucray** [comment]
Hi @qvalero , @wswebcreation ,
I'm using it a lot on Android, migrated from V6 to V7, from sync to async.
Works like a charm.
We haven't had the chance to confirm that on IOS yet, though.

here is a code sample of our integration, async mode :
```
return await driver.compareScreen(imgFileName).then(async (result) => {
      return await expect(result.misMatchPercentage).toBeLessThanOrEqual(percentageTolerance);
    });
```

Thanks for that library, extremely usefull !
Someday directly plugged to WebdriverIO project ?

regards

**Comment by wswebcreation** [comment]
Thanks for confirming!
