### ISSUE TITLE
iPhone home indicator diff

### ISSUE THREAD

**Issue by EduardoNogueira** [wswebcreation/wdio-native-app-compare#23]
**Environment (please complete the following information):**
 - Node.js version: 16.13.2
 - NPM version: 8.1.2
 - webdriver.io version: 7.13.0
 - wdio-native-app-compare-service version: 1.2.0

**Config of webdriver.io and the plugin**
```
[
    "native-app-compare",
    {
      baselineFolder: join(process.cwd(), "./native-visual-tests-baseline/baselines/"),
      imageNameFormat: "{tag}-{platformName}-{deviceName}-{platformVersion}-{orientation}",
      screenshotPath: join(process.cwd(), "./visual-specs/"),
      blockOutStatusBar: true,
      blockOutIphoneXBottomBar: true,
      savePerInstance: true,
      autoSaveBaseline: true,
    },
],
```

**Describe the bug**
I am running visual tests on an iPhone 12 and I always have diffs in the home indicator bar

**Expected behavior**
When comparing the screenshots with the baseline ignore any diff in the home indicator bar

**Screenshots**

![image](https://user-images.githubusercontent.com/3798966/172662247-5e199319-10e8-42d3-a96a-49967d5e352a.png)

**Comment by wswebcreation** [comment]
Thanks for this issue, this is a bug because the iPhone 12 and up are not supported. I need to fix this, but feel free to create a PR

**Comment by EduardoNogueira** [comment]
Can you give me some guidance on how to add support for new iPhones?

**Comment by wswebcreation** [comment]
Hi @EduardoNogueira 

It should be changed here https://github.com/wswebcreation/wdio-native-app-compare/blob/b80930208e70472ce3701ad9a796e44337d2f144/lib/methods/getDeviceInfo.js#L68 based on this https://github.com/wswebcreation/wdio-native-app-compare/blob/master/lib/helpers/constants.js

The list needs to be extended in a more generic way

**Comment by wswebcreation** [comment]
Hi @EduardoNogueira 

I've released version https://github.com/wswebcreation/wdio-native-app-compare/releases/tag/v2.0.0, which holds some more fixes
